<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<?php
/**
 * @var $block \Alekseon\CustomFormsFrontend\Block\Adminhtml\Form\Edit\Tab\FrontendViews
 */
?>
<divc class="messages">
    <div class="message">
        <span><?= __('@here frontend views explanation'); ?></span>
    </div>
</divc>
<div class="page-actions-buttons">
    <?= $block->getChildHtml('add_button'); ?>
</div>
<?= $block->getChildHtml('grid'); ?>
<div id="frontendViewsModal"></div>
<script type="text/x-magento-init">
    {
        "*": {
            "Alekseon_CustomFormsFrontend/js/form/edit/frontend_views": {
                "add_button": "#add_frontend_view_button",
                "modalUrl": "<?= $block->getUrl('alekseon_customFormsFrontend/form_frontendView', ['form_id' => $block->getFormId()]) ?>",
                "saveUrl": "<?= $block->getUrl('alekseon_customFormsFrontend/form_frontendView/save', ['form_id' => $block->getFormId()]) ?>",
                "deleteUrl": "<?= $block->getUrl('alekseon_customFormsFrontend/form_frontendView/delete', ['form_id' => $block->getFormId()]) ?>",
                "modalId": "#frontendViewsModal",
                "formId": "#frontend_view_form",
                "gridJsName": "<?= $block->getChildBlock('grid')->getChildBlock('grid')->getJsObjectName() ?>"
            }
        }
    }
</script>
