<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */

/**
 * @var $block \Alekseon\CustomFormsFrontend\Block\Form\Field\Checkbox
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<div class="control <?= count($block->getOptions()) > 12 ? 'multi-columns' : '' ?> <?= $block->getContainerClass() ?>">
    <?php foreach ($block->getOptions() as $optionId => $optionLabel): ?>
        <div class="checkbox-container">
            <input
                type="checkbox"
                name="<?= $escaper->escapeHtmlAttr($block->getName()) ?>[]"
                id="<?= $escaper->escapeHtmlAttr($block->getId() . '-option-' . $optionId) ?>"
                value="<?= $escaper->escapeHtmlAttr($optionId) ?>"
                <?php if ($block->isSelected($optionId)): ?>checked<?php endif ?>
                data-validate=<?= $block->getDataValidateJson() ?>
            >
                <label for="<?= $escaper->escapeHtmlAttr($block->getId() . '-option-' . $optionId) ?>">
                    <?= $escaper->escapeHtml($optionLabel, $block->getLabelAllowedTags()) ?>
                </label>
            </input>
        </div>
    <?php endforeach; ?>
    <?php if ($note = $block->getNote()): ?>
        <p id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>_note" class="note"><?= $escaper->escapeHtml($note) ?></p>
    <?php endif ?>
</div>
