<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */

/**
 * @var $block \Alekseon\CustomFormsFrontend\Block\Form\Field\Date
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<div class="control <?= $block->getContainerClass() ?>">
    <input
        name="<?= $escaper->escapeHtmlAttr($block->getName()) ?>"
        id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>"
        title="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"
        type="date"
        placeholder="<?= $escaper->escapeHtmlAttr($block->getPlaceholder()) ?>"
        data-validate=<?= $block->getDataValidateJson() ?>
    />
    <?php if ($note = $block->getNote()): ?>
        <p id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>_note" class="note"><?= $escaper->escapeHtml($note) ?></p>
    <?php endif ?>
</div>
