<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */

/**
 * @var $block \Alekseon\CustomFormsFrontend\Block\Form\Field\Select
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<div class="control <?= $block->getContainerClass() ?>">
    <select
        name="<?= $escaper->escapeHtml($block->getName()) ?>"
        id="<?= $escaper->escapeHtml($block->getId()) ?>"
        title="<?= $escaper->escapeHtml($block->getLabel()) ?>"
        data-validate=<?= $block->getDataValidateJson() ?>
    >
        <?php if ($block->hasEmptyOption()): ?>
            <option value=""><?= $escaper->escapeHtmlAttr($block->getEmptyOptionLabel()) ?></option>
        <?php endif ?>
        <?php foreach ($block->getOptions() as $optionId => $optionLabel): ?>
            <option value="<?= $escaper->escapeHtmlAttr($optionId) ?>" <?php if ($block->isSelected($optionId)): ?>selected<?php endif ?>>
                <?= $escaper->escapeHtml($optionLabel) ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
<?php if ($note = $block->getNote()): ?>
    <p id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>_note" class="note"><?= $escaper->escapeHtml($note) ?></p>
<?php endif ?>
