<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */

/**
 * @var $block \Alekseon\CustomFormsFrontend\Block\Form\Field\Textarea
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<div class="control <?= $block->getContainerClass() ?>">
    <textarea
        name="<?= $escaper->escapeHtmlAttr($block->getName()) ?>"
        id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>"
        title="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"
        cols="5"
        rows="3"
        class="<?= $escaper->escapeHtmlAttr($block->getValidationClass()) ?>"
        placeholder="<?= $escaper->escapeHtmlAttr($block->getPlaceholder()) ?>"
        <?php if ($block->getMaxLength()): ?>
            maxlength="<?= $escaper->escapeHtmlAttr($block->getMaxLength()) ?>"
        <?php endif ?>
        data-validate=<?= $block->getDataValidateJson() ?>
    ><?= $escaper->escapeHtml($block->getDefaultValue()) ?></textarea>
    <?php if ($note = $block->getNote()): ?>
        <p id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>_note" class="note"><?= $escaper->escapeHtml($note) ?></p>
    <?php endif ?>
</div>
