<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */

/**
 * @var $block \Alekseon\CustomFormsFrontend\Block\Form\Field
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php if ($block->getInputBlock() && $block->getInputBlock()->displayLabel()): ?>
    <label class="label" for="<?= $escaper->escapeHtmlAttr($block->getInputBlock()->getId()) ?>">
        <?= $escaper->escapeHtml($block->getInputBlock()->getLabel(), $block->getInputBlock()->getLabelAllowedTags()) ?>
    </label>
<?php endif ?>
<?= $block->getChildHtml('field_input') ?>
