<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */

/**
 * @var $block \Alekseon\CustomFormsFrontend\Block\Form\Field
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<div class="field <?= $escaper->escapeHtml($block->getInputBlock()->getFieldClass()) ?>">
    <?php if ($block->getInputBlock() && $block->getInputBlock()->displayLabel()): ?>
        <label class="label" for="<?= $escaper->escapeHtmlAttr($block->getInputBlock()->getId()) ?>"><?= $escaper->escapeHtml($block->getInputBlock()->getLabel()) ?></label>
    <?php endif ?>
    <?= $block->getChildHtml('field_input') ?>
</div>
